<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Fin_filtro</name>
   <tag></tag>
   <elementGuidId>1a42d81c-8bd1-492a-a969-9fe70f6cc106</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vFECFIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vFECFIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d0b5e447-fc53-48c4-a1f6-c5a536c2028d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c8e3fda4-2e6a-4e1d-b6d4-0826d16ffd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vFECFIN</value>
      <webElementGuid>a54be998-9cf9-413d-abe9-c751704a5bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vFECFIN</value>
      <webElementGuid>467030a7-a62a-4e40-a2df-7b890cec70ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>06/03/23</value>
      <webElementGuid>85b1bf10-b0b3-4455-91dd-bc0b34cb559b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>11f05e21-8a89-49ed-b5c9-79d8f58fb7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>19d6a043-4f23-4b33-8705-55f15bdfe4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>589ca0ee-a2e1-44a6-ba64-0ed4d514ba01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AttributeDate form-control</value>
      <webElementGuid>c107b0b8-371b-4c0b-911c-11c3f3a6ea4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 31,'',false,'0001',0)</value>
      <webElementGuid>7a6bb839-b1ee-46db-bc36-4ca75daf2282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 8,'DMY',0,24,'spa',false,0);;gx.evt.onchange(this, event)</value>
      <webElementGuid>7e1deb42-e609-48f0-b779-0651b3b5a1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 8,'DMY',0,24,'spa',false,0);;gx.evt.onblur(this,31);</value>
      <webElementGuid>bea301e9-73be-42ad-879b-58d11f74fc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>9258c976-6612-4e77-96cc-353117d2a477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vFECFIN&quot;)</value>
      <webElementGuid>2347fe2b-e21c-4487-afd2-5ae6b0dcf509</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vFECFIN']</value>
      <webElementGuid>49c4093b-34aa-497e-b82b-acfaa6a0be6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vFECFIN_dp_container']/div/input</value>
      <webElementGuid>db0699fe-89f4-437a-8fc5-cf5a4a5dbda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>83111169-2832-4b3e-860b-5756142680ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'vFECFIN' and @name = 'vFECFIN']</value>
      <webElementGuid>9ad576dd-a03a-4355-9895-e32dada0b572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
