<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Fecha Inicio_filtro</name>
   <tag></tag>
   <elementGuidId>6519ada4-8c47-4b03-9912-b295e0d01348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vFECINI']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vFECINI</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33c5dfe7-6d06-40e8-b2f5-fe5175713470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5932c736-1c1b-4bd4-bd86-09ea4c433236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vFECINI</value>
      <webElementGuid>f287dc18-fb91-480c-b087-5c40e4ee1b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vFECINI</value>
      <webElementGuid>1c406b39-6d61-4f67-80f4-e4538cf721a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>06/03/23</value>
      <webElementGuid>df7e7c04-0723-4cba-a643-2e84802826e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>52b5856b-f240-4389-be8c-3e947f313473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff1ccf99-f3dc-428e-82da-791017503635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>f625e3de-a761-4cb8-ae16-b822b79af09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>AttributeDate form-control</value>
      <webElementGuid>3de17848-75e5-4b2c-9eea-b745e2b5698a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 27,'',false,'0001',0)</value>
      <webElementGuid>000e70bb-3e13-4ea8-9af6-bb89076eed22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 8,'DMY',0,24,'spa',false,0);;gx.evt.onchange(this, event)</value>
      <webElementGuid>dac0cfe4-0693-4a15-bf00-9b49529a17ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.date.valid_date(this, 8,'DMY',0,24,'spa',false,0);;gx.evt.onblur(this,27);</value>
      <webElementGuid>664c262e-6f15-4719-9953-de1876b4ec4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>e6ea802b-e893-4860-8942-8ed015ef8a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vFECINI&quot;)</value>
      <webElementGuid>5e51916e-aceb-4041-bd07-b7f77e83a25d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vFECINI']</value>
      <webElementGuid>8ea4b905-abcc-4acf-8edf-40120679de44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vFECINI_dp_container']/div/input</value>
      <webElementGuid>e0c81154-8547-4283-b091-8d71fcb32538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ee8f05eb-782c-4cfd-92dc-fbbfd0448c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'vFECINI' and @name = 'vFECINI']</value>
      <webElementGuid>41083300-0bd5-4b9b-8ee2-44e0e7a485be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
