<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Importe_filtro</name>
   <tag></tag>
   <elementGuidId>beb750b5-d745-4993-b2f5-fbb5232d573f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='vIMPORTE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#vIMPORTE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68d84dac-e50a-4764-9162-f3cfe2fa6718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99d6a3ef-99a3-47f5-b9c8-acdf24fb181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vIMPORTE</value>
      <webElementGuid>9fb0895f-9119-4e71-97ae-2bb2f750b99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vIMPORTE</value>
      <webElementGuid>34d8efd8-0a8f-4cfd-8fbe-4d81b76a622f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10.000,00</value>
      <webElementGuid>2448dad4-c093-4b49-bf5c-70629b20424c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>7ab77618-ea5d-4a9b-91c3-bb513ea27397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ce0766eb-8231-4528-acdd-5f1b80f189c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>54c0a95c-0719-43cb-a693-875d0d045d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Attribute form-control</value>
      <webElementGuid>93b81001-d527-4bd1-bca1-b6f345ca4d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>gx.evt.onfocus(this, 35,'',false,'0001',0)</value>
      <webElementGuid>cae6f59d-22dc-4e5e-9b23-a83c6f96fb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.num.valid_decimal( this, '.',',','5');;gx.evt.onchange(this, event)</value>
      <webElementGuid>646b0fb9-acef-47ad-a7ae-15abbf3c5171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>gx.num.valid_decimal( this, '.',',','5');;gx.evt.onblur(this,35);</value>
      <webElementGuid>babf5c20-d637-4c80-bb67-d6884cd05790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-context</name>
      <type>Main</type>
      <value>[&quot;&quot;,false]</value>
      <webElementGuid>a950b933-9320-40d6-b62a-e7157fe3a991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vIMPORTE&quot;)</value>
      <webElementGuid>5cee8e4c-d6f4-4132-8ffd-9c3298513dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='vIMPORTE']</value>
      <webElementGuid>3ac6751d-077b-4dae-8403-e678c5794519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='TABLEFILTERS']/div/div[3]/div/div/input</value>
      <webElementGuid>df168906-0071-4d83-963e-207d6d7994e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>0e144d3e-ea08-4701-ace2-f220ff52aeab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'vIMPORTE' and @name = 'vIMPORTE']</value>
      <webElementGuid>489a6d0a-474f-43aa-91b0-3111cab95484</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
