<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Cantidad</name>
   <tag></tag>
   <elementGuidId>89fbd50e-17f1-4770-94a0-dbe19ea45b74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_vCANTIDAD_0001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#span_vCANTIDAD_0001</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1f041b56-ce33-4a7c-b0d5-a37dbaf6ed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>9207a089-9c98-46bf-b723-760e6d720d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>[0-9]*</value>
      <webElementGuid>9e554ed4-d83b-4256-a65d-ea7c7d00db1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.num.valid_integer( this,'.');;gx.evt.onchange(this, event)</value>
      <webElementGuid>42444047-3811-4729-b69a-26a80d9d388d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReadonlyAttribute</value>
      <webElementGuid>daa3b736-59d4-4f93-964a-345b120697fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>span_vCANTIDAD_0001</value>
      <webElementGuid>821b5997-a032-4e7b-8c5b-5cc759163f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-enabled-id</name>
      <type>Main</type>
      <value>vCANTIDAD_0001</value>
      <webElementGuid>5953ea15-6fb7-447f-8294-70f2944c3a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>89</value>
      <webElementGuid>8503badf-1804-4b23-ab64-874862e05ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_vCANTIDAD_0001&quot;)</value>
      <webElementGuid>e9d9c582-dea8-42d0-888b-f323d3fea4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='span_vCANTIDAD_0001']</value>
      <webElementGuid>0db3dc1c-d379-443f-a6a7-e15b9b91797e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='GridContainerRow_0001']/td[6]/p/span</value>
      <webElementGuid>391e0f4c-066f-4645-8da5-c366000df652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WUHL HEIDT, MARIIO'])[1]/following::span[2]</value>
      <webElementGuid>f1f003e0-2756-40e3-bc6a-5766e621fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver Operaciones'])[1]/following::span[6]</value>
      <webElementGuid>c3c0e152-f22d-4102-80c3-c27b6196bd73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDIO'])[1]/preceding::span[1]</value>
      <webElementGuid>a0a85a14-c7d8-4203-b377-7570e29e705e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Física'])[1]/preceding::span[2]</value>
      <webElementGuid>c84b5fdf-af70-4a7e-aa7d-ec4b12727021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='89']/parent::*</value>
      <webElementGuid>57ddbb28-f2a9-49a7-b515-54cea523d902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/p/span</value>
      <webElementGuid>e6d2f857-3be7-4369-9843-a28d135fefcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'span_vCANTIDAD_0001' and (text() = '89' or . = '89')]</value>
      <webElementGuid>d1b25292-74b8-4656-a1b3-6e4a6f9db115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
