<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Importe</name>
   <tag></tag>
   <elementGuidId>1ee86439-eeb8-4fae-bd46-333057500a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='span_vMONTO_0001']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#span_vMONTO_0001</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cf563fe5-e960-4225-a58d-a2c818a95691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gx.num.valid_decimal( this, '.',',','2');;gx.evt.onchange(this, event)</value>
      <webElementGuid>3912653b-7198-4539-bc0d-3c97424bf5a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ReadonlyAttribute</value>
      <webElementGuid>abad5ee9-9dc6-4682-886a-8603ce477333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>span_vMONTO_0001</value>
      <webElementGuid>0a210257-bb82-4964-9f00-10c762f2cf84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gx-enabled-id</name>
      <type>Main</type>
      <value>vMONTO_0001</value>
      <webElementGuid>26a27fea-e3b9-4e41-9a7d-1d450a94f444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7358,53</value>
      <webElementGuid>fa3eb432-f58f-4d8f-b5c7-94a206c4ca76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;span_vMONTO_0001&quot;)</value>
      <webElementGuid>ef40ae20-013f-4459-ab1a-f55f453a63d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='span_vMONTO_0001']</value>
      <webElementGuid>e8e499ed-8861-4f31-bf6d-8b24c4388162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='GridContainerRow_0001']/td[5]/p/span</value>
      <webElementGuid>5c5459c4-5f10-4712-b67c-41f54586028e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WUHL HEIDT, MARIIO'])[1]/following::span[1]</value>
      <webElementGuid>390283d7-1798-4412-be94-25eddca0f5cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver Operaciones'])[1]/following::span[5]</value>
      <webElementGuid>4c093e18-aad4-4492-b77c-c80f48e6ec5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEDIO'])[1]/preceding::span[2]</value>
      <webElementGuid>b62d8ff8-dc60-44e2-8c5b-b1775534bd02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Física'])[1]/preceding::span[3]</value>
      <webElementGuid>ba2dde35-452f-436f-9393-9bba0d7676e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7358,53']/parent::*</value>
      <webElementGuid>add7673b-693e-4919-b6c3-664e5fe67af2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/p/span</value>
      <webElementGuid>86b8ab96-c34a-4b63-ac37-9e4576a2ebe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'span_vMONTO_0001' and (text() = '7358,53' or . = '7358,53')]</value>
      <webElementGuid>d1d49b8e-95c1-471e-b1e0-bf09b788923c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
